# Generated by Django 4.1.7 on 2023-04-01 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_hackathons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('background_image', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('hackathon_image_logo', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('submission_type', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reward_prize', models.CharField(blank=True, max_length=200, null=True)),
                ('github_repository', models.URLField()),
                ('other_links', models.URLField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(blank=True, max_length=200, null=True)),
                ('enrolled_hackathon', models.CharField(blank=True, max_length=200, null=True)),
                ('submission_name', models.CharField(blank=True, max_length=200, null=True)),
                ('submission_summary', models.TextField(blank=True, null=True)),
                ('submission_as_link', models.URLField()),
                ('submission_as_file', models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('submission_as_image', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('date_of_submission', models.DateField(auto_now_add=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hackathon_Registeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(blank=True, max_length=200, null=True)),
                ('enrolled_hackathon', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_registration', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
