# Generated by Django 4.1.7 on 2023-04-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_hackathons',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='create_hackathons',
            name='hackathon_image_logo',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_as_file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_as_image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
