# Generated by Django 4.1.7 on 2023-04-02 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon_api', '0002_alter_create_hackathons_background_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='participant_name',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission_as_file',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission_as_image',
        ),
    ]
