# Generated by Django 4.1.7 on 2023-04-02 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hackathon_api', '0003_remove_submission_participant_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_hackathon', models.CharField(blank=True, max_length=200, null=True)),
                ('submission_name', models.CharField(blank=True, max_length=200, null=True)),
                ('submission_summary', models.TextField(blank=True, null=True)),
                ('date_of_submission', models.DateField(auto_now_add=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
