# Generated by Django 4.1.7 on 2023-04-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon_api', '0004_submissions_delete_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='submission_as_file',
            field=models.FileField(blank=True, default=None, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='submissions',
            name='submission_as_link',
            field=models.URLField(default=None),
        ),
    ]
