# Generated by Django 4.1.7 on 2023-04-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon_api', '0007_submissions_submission_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathon_registeration',
            old_name='user',
            new_name='participant',
        ),
    ]
