# Generated by Django 4.1.7 on 2023-04-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon_api', '0008_rename_user_hackathon_registeration_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon_registeration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
