# Generated by Django 4.1.7 on 2023-04-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon_api', '0009_alter_hackathon_registeration_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='favourite',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
